import { subDays } from "date-fns";

const now = new Date();
const d = (offsetDays, h = 10, m = 0) => {
  const dt = subDays(now, offsetDays);
  dt.setHours(h, m, 0, 0);
  return dt.toISOString();
};

export const MOCK_USERS = [
  {
    id: 1,
    name: "Vikram Sharma",
    role: "boss",
    passcode: "1234",
    macAddress: "AA:BB:CC:DD:EE:01",
  },
  {
    id: 2,
    name: "Anita Singh",
    role: "manager",
    passcode: "2345",
    macAddress: "AA:BB:CC:DD:EE:02",
  },
  {
    id: 3,
    name: "Ramesh Kumar",
    role: "employee",
    passcode: "3456",
    macAddress: "AA:BB:CC:DD:EE:03",
  },
  {
    id: 4,
    name: "Pooja Verma",
    role: "employee",
    passcode: "4567",
    macAddress: "AA:BB:CC:DD:EE:04",
  },
  {
    id: 5,
    name: "Suresh Patel",
    role: "manager",
    passcode: "5678",
    macAddress: "AA:BB:CC:DD:EE:05",
  },
];

export const MOCK_UNITS = [
  { id: 1, name: "Kilogram", abbr: "kg" },
  { id: 2, name: "Gram", abbr: "g" },
  { id: 3, name: "Litre", abbr: "L" },
  { id: 4, name: "Piece", abbr: "pc" },
  { id: 5, name: "Dozen", abbr: "doz" },
  { id: 6, name: "Bag", abbr: "bag" },
  { id: 7, name: "Carton", abbr: "ctn" },
];

export const MOCK_LOCATIONS = [
  { id: 1, name: "Main Shop" },
  { id: 2, name: "Godown 1" },
  { id: 3, name: "Basement" },
];

export const MOCK_ITEMS = [
  {
    id: 1,
    name: "Basmati Rice",
    defaultPrice: 65,
    unitId: 1,
    status: "active",
  },
  { id: 2, name: "Toor Dal", defaultPrice: 110, unitId: 1, status: "active" },
  {
    id: 3,
    name: "Sunflower Oil",
    defaultPrice: 140,
    unitId: 3,
    status: "active",
  },
  {
    id: 4,
    name: "Wheat Flour (Atta)",
    defaultPrice: 42,
    unitId: 1,
    status: "active",
  },
  { id: 5, name: "Sugar", defaultPrice: 45, unitId: 1, status: "active" },
  { id: 6, name: "Salt (Tata)", defaultPrice: 22, unitId: 6, status: "active" },
  {
    id: 7,
    name: "Mustard Oil",
    defaultPrice: 165,
    unitId: 3,
    status: "active",
  },
  { id: 8, name: "Moong Dal", defaultPrice: 95, unitId: 1, status: "active" },
  { id: 9, name: "Chana Dal", defaultPrice: 88, unitId: 1, status: "active" },
  {
    id: 10,
    name: "Biscuits (Parle-G)",
    defaultPrice: 10,
    unitId: 4,
    status: "active",
  },
  {
    id: 11,
    name: "Tea (Red Label)",
    defaultPrice: 280,
    unitId: 6,
    status: "active",
  },
  {
    id: 12,
    name: "Detergent (Nirma)",
    defaultPrice: 55,
    unitId: 4,
    status: "active",
  },
  { id: 13, name: "Soap (Lux)", defaultPrice: 35, unitId: 4, status: "active" },
  {
    id: 14,
    name: "Coconut Oil",
    defaultPrice: 190,
    unitId: 3,
    status: "active",
  },
  {
    id: 15,
    name: "Milk Powder (Amul)",
    defaultPrice: 320,
    unitId: 6,
    status: "inactive",
  },
];

export const MOCK_INVENTORY = [
  // [itemId, locationId, qty]
  [1, 1, 150],
  [1, 2, 300],
  [1, 3, 0],
  [2, 1, 80],
  [2, 2, 120],
  [3, 1, 45],
  [3, 2, 90],
  [4, 1, 200],
  [4, 2, 150],
  [5, 1, 60],
  [5, 2, 200],
  [6, 1, 40],
  [6, 2, 80],
  [7, 1, 30],
  [7, 2, 60],
  [8, 1, 70],
  [8, 2, 90],
  [9, 1, 55],
  [9, 2, 75],
  [10, 1, 120],
  [10, 2, 200],
  [11, 1, 25],
  [11, 2, 50],
  [12, 1, 60],
  [12, 2, 90],
  [13, 1, 80],
  [14, 1, 20],
  [14, 2, 40],
].map(([itemId, locationId, qty]) => ({ itemId, locationId, qty }));

export const MOCK_ORDERS = [
  {
    id: "ORD-2026-001",
    customerName: "Rajesh Kumar",
    customerPhone: "9876543210",
    isDeliveryOrder: false,
    deliveryAgentName: null,
    status: "completed",
    paymentMethod: "cash",
    totalAmount: 1300,
    discount: 100,
    finalAmount: 1200,
    createdBy: 1,
    completedBy: 2,
    fulfilledBy: [3],
    createdAt: d(0, 9, 15),
    completedAt: d(0, 9, 45),
    items: [
      { itemId: 1, qty: 10, priceApplied: 65, isChecked: true },
      { itemId: 2, qty: 3, priceApplied: 110, isChecked: true },
      { itemId: 5, qty: 5, priceApplied: 45, isChecked: true },
    ],
    notes: "",
  },
  {
    id: "ORD-2026-002",
    customerName: "Sunita Devi",
    customerPhone: "9123456789",
    isDeliveryOrder: true,
    deliveryAgentName: "Ravi Kumar",
    status: "fulfilling",
    paymentMethod: "upi",
    totalAmount: 870,
    discount: 0,
    finalAmount: 870,
    createdBy: 1,
    completedBy: null,
    fulfilledBy: [],
    createdAt: d(0, 10, 30),
    completedAt: null,
    items: [
      { itemId: 3, qty: 2, priceApplied: 140, isChecked: true },
      { itemId: 4, qty: 5, priceApplied: 42, isChecked: true },
      { itemId: 11, qty: 1, priceApplied: 280, isChecked: false },
    ],
    notes: "Deliver to Shiv Colony, near water tank",
  },
  {
    id: "ORD-2026-003",
    customerName: "Mohammed Irfan",
    customerPhone: "9988776655",
    isDeliveryOrder: false,
    deliveryAgentName: null,
    status: "pending",
    paymentMethod: null,
    totalAmount: 650,
    discount: 0,
    finalAmount: 650,
    createdBy: 1,
    completedBy: null,
    fulfilledBy: [],
    createdAt: d(0, 11, 5),
    completedAt: null,
    items: [
      { itemId: 7, qty: 2, priceApplied: 165, isChecked: false },
      { itemId: 8, qty: 2, priceApplied: 95, isChecked: false },
      { itemId: 9, qty: 1, priceApplied: 88, isChecked: false },
      { itemId: 6, qty: 3, priceApplied: 22, isChecked: false },
    ],
    notes: "",
  },
  {
    id: "ORD-2026-004",
    customerName: "Priya Gupta",
    customerPhone: "9765432100",
    isDeliveryOrder: false,
    deliveryAgentName: null,
    status: "completed",
    paymentMethod: "credit",
    totalAmount: 2100,
    discount: 200,
    finalAmount: 1900,
    createdBy: 1,
    completedBy: 2,
    fulfilledBy: [4],
    createdAt: d(1, 14, 20),
    completedAt: d(1, 14, 55),
    items: [
      { itemId: 1, qty: 20, priceApplied: 62, isChecked: true },
      { itemId: 2, qty: 5, priceApplied: 108, isChecked: true },
      { itemId: 14, qty: 2, priceApplied: 185, isChecked: true },
    ],
    notes: "",
  },
  {
    id: "ORD-2026-005",
    customerName: "Harish Yadav",
    customerPhone: "9654321098",
    isDeliveryOrder: false,
    deliveryAgentName: null,
    status: "partial",
    paymentMethod: "cash",
    totalAmount: 980,
    discount: 0,
    finalAmount: 980,
    createdBy: 1,
    completedBy: 5,
    fulfilledBy: [3],
    createdAt: d(1, 16, 10),
    completedAt: d(1, 16, 45),
    items: [
      { itemId: 4, qty: 10, priceApplied: 42, isChecked: true },
      { itemId: 5, qty: 8, priceApplied: 45, isChecked: true },
      { itemId: 3, qty: 1, priceApplied: 140, isChecked: false },
    ],
    notes: "Oil out of stock — will deliver tomorrow",
  },
  {
    id: "ORD-2026-006",
    customerName: "Kavita Joshi",
    customerPhone: "9543210987",
    isDeliveryOrder: false,
    deliveryAgentName: null,
    status: "completed",
    paymentMethod: "mixed",
    totalAmount: 1540,
    discount: 40,
    finalAmount: 1500,
    createdBy: 1,
    completedBy: 2,
    fulfilledBy: [3, 4],
    createdAt: d(2, 11, 0),
    completedAt: d(2, 11, 30),
    items: [
      { itemId: 1, qty: 10, priceApplied: 65, isChecked: true },
      { itemId: 11, qty: 2, priceApplied: 280, isChecked: true },
      { itemId: 12, qty: 5, priceApplied: 55, isChecked: true },
      { itemId: 13, qty: 4, priceApplied: 35, isChecked: true },
    ],
    notes: "",
  },
];

export const MOCK_CUSTOMERS = [
  {
    id: 1,
    name: "Priya Gupta",
    phone: "9765432100",
    totalOwed: 1900,
    totalPaid: 500,
    transactions: [
      {
        id: 1,
        orderId: "ORD-2026-004",
        type: "credit",
        amount: 1900,
        date: d(1, 14, 55),
        note: "Order credit",
      },
      {
        id: 2,
        orderId: null,
        type: "payment",
        amount: 500,
        date: d(0, 10, 0),
        note: "Cash payment",
      },
    ],
  },
  {
    id: 2,
    name: "Deepak Mehta",
    phone: "9432109876",
    totalOwed: 3200,
    totalPaid: 1000,
    transactions: [
      {
        id: 3,
        orderId: "ORD-2026-007",
        type: "credit",
        amount: 2000,
        date: d(5, 11, 0),
        note: "Order credit",
      },
      {
        id: 4,
        orderId: "ORD-2026-008",
        type: "credit",
        amount: 1200,
        date: d(3, 15, 0),
        note: "Order credit",
      },
      {
        id: 5,
        orderId: null,
        type: "payment",
        amount: 1000,
        date: d(1, 9, 0),
        note: "UPI payment",
      },
    ],
  },
  {
    id: 3,
    name: "Rekha Sharma",
    phone: "9321098765",
    totalOwed: 650,
    totalPaid: 650,
    transactions: [
      {
        id: 6,
        orderId: "ORD-2026-009",
        type: "credit",
        amount: 650,
        date: d(7, 14, 0),
        note: "Order credit",
      },
      {
        id: 7,
        orderId: null,
        type: "payment",
        amount: 650,
        date: d(4, 10, 0),
        note: "Cash payment",
      },
    ],
  },
];

export const MOCK_DAILY_LEDGER = [
  {
    date: d(0),
    isCommitted: false,
    isCorrected: false,
    orders: [
      {
        orderId: "ORD-2026-001",
        finalAmount: 1200,
        paymentMethod: "cash",
        customerName: "Rajesh Kumar",
        verifiedBy: 2,
      },
      {
        orderId: "ORD-2026-002",
        finalAmount: 870,
        paymentMethod: "upi",
        customerName: "Sunita Devi",
        verifiedBy: null,
      },
    ],
    totalCash: 1200,
    totalUpi: 0,
    totalCredit: 0,
    grandTotal: 1200,
  },
  {
    date: d(1),
    isCommitted: true,
    isCorrected: false,
    orders: [
      {
        orderId: "ORD-2026-004",
        finalAmount: 1900,
        paymentMethod: "credit",
        customerName: "Priya Gupta",
        verifiedBy: 2,
      },
      {
        orderId: "ORD-2026-005",
        finalAmount: 980,
        paymentMethod: "cash",
        customerName: "Harish Yadav",
        verifiedBy: 5,
      },
    ],
    totalCash: 980,
    totalUpi: 0,
    totalCredit: 1900,
    grandTotal: 2880,
  },
  {
    date: d(2),
    isCommitted: true,
    isCorrected: false,
    orders: [
      {
        orderId: "ORD-2026-006",
        finalAmount: 1500,
        paymentMethod: "mixed",
        customerName: "Kavita Joshi",
        verifiedBy: 2,
      },
    ],
    totalCash: 750,
    totalUpi: 750,
    totalCredit: 0,
    grandTotal: 1500,
  },
];

export const MOCK_ATTENDANCE = [
  {
    id: 1,
    userId: 2,
    date: d(0),
    checkIn: "09:05",
    checkOut: "18:30",
    markedBy: 2,
    status: "present",
  },
  {
    id: 2,
    userId: 3,
    date: d(0),
    checkIn: "09:10",
    checkOut: "18:15",
    markedBy: 2,
    status: "present",
  },
  {
    id: 3,
    userId: 4,
    date: d(0),
    checkIn: "09:20",
    checkOut: null,
    markedBy: 2,
    status: "present",
  },
  {
    id: 4,
    userId: 5,
    date: d(0),
    checkIn: null,
    checkOut: null,
    markedBy: 2,
    status: "absent",
  },
  {
    id: 5,
    userId: 2,
    date: d(1),
    checkIn: "09:00",
    checkOut: "18:00",
    markedBy: 2,
    status: "present",
  },
  {
    id: 6,
    userId: 3,
    date: d(1),
    checkIn: "09:30",
    checkOut: "18:30",
    markedBy: 2,
    status: "present",
  },
  {
    id: 7,
    userId: 4,
    date: d(1),
    checkIn: null,
    checkOut: null,
    markedBy: 2,
    status: "absent",
  },
  {
    id: 8,
    userId: 5,
    date: d(1),
    checkIn: "09:05",
    checkOut: "18:10",
    markedBy: 2,
    status: "present",
  },
];

// Sales velocity (30 days)
export const MOCK_VELOCITY = [
  { itemId: 1, sold7: 350, sold14: 680, sold30: 1450 },
  { itemId: 2, sold7: 90, sold14: 175, sold30: 380 },
  { itemId: 3, sold7: 55, sold14: 100, sold30: 220 },
  { itemId: 4, sold7: 280, sold14: 540, sold30: 1100 },
  { itemId: 5, sold7: 210, sold14: 390, sold30: 820 },
  { itemId: 6, sold7: 60, sold14: 115, sold30: 245 },
  { itemId: 7, sold7: 40, sold14: 78, sold30: 165 },
  { itemId: 8, sold7: 70, sold14: 135, sold30: 285 },
  { itemId: 9, sold7: 50, sold14: 95, sold30: 200 },
  { itemId: 10, sold7: 400, sold14: 780, sold30: 1600 },
  { itemId: 11, sold7: 35, sold14: 68, sold30: 145 },
  { itemId: 12, sold7: 80, sold14: 155, sold30: 320 },
];

// Notifications (7-day TTL)
export const MOCK_NOTIFICATIONS = [
  {
    id: 1,
    type: "new_order",
    title: "New Order #ORD-006",
    message: "Sunita Devi placed an order for Rice (10kg), Dal (2kg)",
    orderId: 6,
    read: false,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      { name: "Rice", location: "Main Shop – Rack A2" },
      { name: "Dal", location: "Main Shop – Rack B1" },
    ],
  },
  {
    id: 2,
    type: "order_update",
    title: "Order #ORD-004 is being fulfilled",
    message: "Manager Priya started fulfilling the order",
    orderId: 4,
    read: true,
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    items: [],
  },
  {
    id: 3,
    type: "stock_alert",
    title: "Low Stock: Salt",
    message: "Salt stock is below reorder level at Main Shop",
    orderId: null,
    read: false,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), // expired
    items: [{ name: "Salt", location: "Main Shop – Rack C3" }],
  },
];

// Daily revenue for charts (last 7 days)
export const MOCK_REVENUE_CHART = [
  { date: "20 Feb", revenue: 4800, orders: 8 },
  { date: "21 Feb", revenue: 6200, orders: 11 },
  { date: "22 Feb", revenue: 3900, orders: 7 },
  { date: "23 Feb", revenue: 7100, orders: 13 },
  { date: "24 Feb", revenue: 5500, orders: 9 },
  { date: "25 Feb", revenue: 2880, orders: 5 },
  { date: "26 Feb", revenue: 1200, orders: 2 },
];
